---
- hosts: '{{ host }}'
  become: true
  become_user: root
  become_method: sudo
  gather_facts: false
  tasks:
    - name: Install Python SDK for Docker
      yum:
        name:
          - python-docker-py
          - python3 
          - python3-pip
        state: present

    - name: pip install pyOpenSSL
      pip:
        name: pyOpenSSL
        executable: pip3

    - name: Generate a Self Signed OpenSSL certificate
      openssl_certificate:
        path: /registry/ssl/registry.crt
        privatekey_path: /registry/ssl/registry.pem
        csr_path: /registry/ssl/registry.csr
        provider: selfsigned

    - name: Run Docker Registry Server
      docker_container:
        name: registry
        image: registry:2
        published_ports: 5000:5000
        restart_policy: always
        state: started
