---
- hosts: '{{ host }}'
  become: true
  become_user: root
  become_method: sudo
  gather_facts: false
  tasks:
    - name: Install required system packages
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
    
    - name: Install Docker
      yum:
        name:
          - docker-ce 
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Start and enable docker-service
      systemd:
        name: docker
        state: started
        enabled: yes

