---
- name: install postgresql repo
  yum:
    name:
      - "{{ postgresql_12_centos7_repo }}"
    state: present

- name: install postgresql server
  yum:
    name:
      - postgresql12-server
    state: present

